### ISSUE TITLE
on_private_message callback do not pass the sender nick

### ISSUE THREAD

**Issue by LaineZ** [gkbrk/JustIRC#1]
on_private_message callback pass only 3 argumets - ``bot handle``, ``bot nickname`` (?), ``message``, why is not there an argument of the sender nickname?

**Comment by gkbrk** [comment]
Can you send an example? It should be getting the JustIRC instance (bot handle), the sender nickname and the message.

**Comment by gkbrk** [comment]
Closed for inactivity
