### ISSUE TITLE
Simple commands and login by password

### ISSUE THREAD

**Issue by MSIKT4AV** [gkbrk/JustIRC#3]
Hi, can you give me example bot (hellobot). Who just greetings users and respond to command like !info ? And i need login by nickname/password but i dont know how

**Comment by MSIKT4AV** [comment]
Ok i add:

    if message.split()[0] == "!info":
        bot.send_message(channel, "info")

It works. Now i need login to irc account with username and password

**Comment by gkbrk** [comment]
I think you can do `bot.send_message("NickServ", "identify 12345")` where `12345` is your password.

**Comment by MSIKT4AV** [comment]
Can you tell where to put this code?

**Comment by MSIKT4AV** [comment]
My first simple version of bot was use:

irc.send(("LOGIN "+botnick+" "+password+"\n").encode())

**Comment by gkbrk** [comment]
@d3jr00 I would put that code to the `on_welcome` handler.

    def on_welcome(bot):
        bot.send_message('NickServ', 'identify 123456')
        bot.join_channel("#TestChannel")

**Comment by MSIKT4AV** [comment]
Hi. After many combinations, only this worked:

```
irc.send(("USER "+botnick+" "+botnick+" "+botnick+" :I'm just a simple bot!\r\n").encode())
time.sleep(1)
irc.send(("NICK "+botnick+"\n").encode())
time.sleep(1)
irc.send(("LOGIN "+botnick+" "+password+"\n").encode())
time.sleep(3)
irc.send(("JOIN "+channel+"\n").encode())
```

Now I'm building a bot in JavaScript. Thanks for the help.
